[package]
name = "rust-scudo"
version = "0.1.0"
edition = "2018"
license-file = "LICENSE.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
